### ISSUE TITLE
some advise

### ISSUE THREAD

**Issue by dx3906999** [UCAS-CTF/ucas-ctf.github.io#11]
感觉是不是c基础可以先讲一下 什么事变量 什么事变量名 什么事变量的值

**Comment by li-yiyang** [comment]
可以用简单的表单模型进行讲解, 这样还方便引入栈和指针的概念:

表单模型: 
+ 变量和值存放在一个表格中: 

  | ID | 变量 | 值  |
  |----|------|-----|
  | 0  | `x`  | `1` |
  | 1  | `y`  | `2` |
+ 通过变量对应的 `ID` 去引用值 -> 指针的概念;
+ 如果有如下情况: 
  + 登陆校园网 `srun_portal_login`
  + 对应变量表单 `srun_info`: 
  
    | ID | 变量       | 值 |
    |----|------------|----|
    | 0  | `username` |    |
    | 1  | `password` |    |
  + 那么对不同用户登陆时, 就需要不同的表单, 如何在一个存储空间中存储这些表单? 
    1. 表单的表单 -> struct 的概念
	
	   | ID  | 变量    | 值                |
	   |-----|---------|-------------------|
	   | 0   | `用户1` | `srun_info user1` |
	   | 1   | `用户2` | `srun_info user2` |
	   | ... |         |                   |
	2. 从上面可以发现, 可以在连续空间中依次按序填充数据, 只要规定每个用户所能访问 (看见) 的表单有限, 即可实现不同用户对应不同变量 -> 栈的概念
	
	   | ID | 变量       | 值 | 可见用户 |
	   |----|------------|----|----------|
	   | 0  | `username` |    | 1        |
	   | 1  | `password` |    | 1        |
	   | 2  | `username` |    | 2        |
	   | 3  | `password` |    | 2        |

       但是这只能防君子, 不能防小人, 凭什么就会限制用户 2 不能去访问 `ID` 为 `0` 和 `1` 的表单中的数据? -> ROP 的概念以及对应的保护措施
    3. 也许不一定是连续空间 -> `malloc` 和堆 -> `glibc` 以及对应的 PWN
	
然后在讲完这个简单模型后, 还是得回到真实计算机的实际的内存模型以及实际的栈的模型.
