### ISSUE TITLE
BUG: Wiki网页框架对于<details>块及内部代码块的渲染有问题

### ISSUE THREAD

**Issue by jiuhao47** [UCAS-CTF/ucas-ctf.github.io#20]
![e96e8d44aaaa2941a12eb0c4b2c4c43a](https://github.com/user-attachments/assets/7ecc7afc-0331-42c8-b321-40a3b4ecda03)
![image](https://github.com/user-attachments/assets/81d8d003-8d75-4d1c-a348-021c8fe39076)
![57c1b0bd8401379e15fb0699dc31e3fb](https://github.com/user-attachments/assets/4aff26df-df50-4382-a47d-b1874c4b1e9c)

图1中显示的即为渲染失败的样子
图2为从github的md渲染界面看到的样子
图3中</details>标签的颜色渲染疑似有些问题（和上面的绿色</details>有不同）

望尽快修复

**Comment by dx3906999** [comment]
\<details\>标签似乎只能在\<p\>标签外渲染正确

**Comment by dx3906999** [comment]
在\<details\>标签外面套一层\<div\>即可

**Comment by jiuhao47** [comment]
![f08630cf6a9830054b8ffbd8dffee49a](https://github.com/user-attachments/assets/8f7ed718-bfd7-4723-ad75-c405bb854c20)

![523b453d2cc47f67ce08e96a945b0606](https://github.com/user-attachments/assets/75564adf-aac5-45ff-8a28-82eb6584c486)

 已尝试，无效

**Comment by dx3906999** [comment]
寄

**Comment by li-yiyang** [comment]
[ref: [Bug]: `<details>` disclosure elements prevent markdown rendering](https://github.com/jekyll/jekyll/issues/9297), 见 PR #30 

(绷: comment 栏竟然也会渲染 HTML... 如果我加入 `<script>` 会如何? 

<script>alert("Haha");</script>

看起来还是做了防护的.
